{{- define "est-mit-payment.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
volumeMounts:
- mountPath: {{ .Values.volumeMounts.mountPath }}
  name: {{ .Values.volumeMounts.name }}
{{- end -}}