version: '3.8'

services:
  est-mit-validation-service:
    build:
      context: .
      target: development
    image: est-mit-validation-service-snyk
    command: extract-project-assets.sh
    entrypoint: /bin/sh
    volumes:
      - ./scripts/extract-project-assets.sh:/home/dotnet/extract-project-assets.sh
      - ./EST.MIT.ValidationService.Api/obj:/home/dotnet/snyk